spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_qa_db
    username: qa_user
    password: qa_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect