spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:~/deliverydb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver


  ai:
    deepseek:
      api-key: "api-key-placeholder"
      chat:
        options:
          model: deepseek-chat

  logging:
    level:
      root: INFO
      com.logistics.delivery_optimizer: DEBUG
      org.hibernate.SQL: DEBUG